Update README.md
uroni/urbackup-server-docker pull request #6
Opened 2022-11-01 17:38 UTC by tvhdev

The optional zfs or btrfs Parameters were missing

2022-11-06 21:27 UTC, uroni commented on entrypoint.sh
> +f [[ $ZFS != "" || $BTRFS != ""]]
I think there is an i missing there

2022-12-15 05:40 UTC, jonct requested changes
Great catch! This is no mere README update. It's following through on getting incremental image backups configured on ZFS and btrfs.

2022-12-15 05:40 UTC, jonct commented on Dockerfile
> +VOLUME [ "/var/urbackup", "/var/log", "/backups","/backup_images" ]
Nitpicky with apologies: match the established space-after-comma?  🙄

2022-12-15 05:40 UTC, jonct commented on entrypoint.sh
> +if [[ $ZFS != "" || $BTRFS != ""]]
More seriously: this won't evaluate correctly without quoting `"$ZFS"` and `"$BTRFS"`.

It might accidentally work by short-circuiting when ZFS is non-null. Otherwise bash would try to evaluate `[[ != "" || != "" ]]` and would complain about syntax.

2022-12-15 05:40 UTC, jonct commented on entrypoint.sh
>  if [[ $PUID != "" ]]
At least you had company.  😉  `"$PUID"` here and `"$PGID"` six lines below.

In this case it might be clearer to replace both if-then-else clauses with defaulting substitutions, as we saw demonstrated at the top of the file:
```
usermod -u ${PUID:-101} -o urbackup
groupmod -g ${PGID:-101} -o urbackup
```

2024-10-18 20:51 UTC, closed without merging